def label = "slave-${UUID.randomUUID().toString()}"

podTemplate(
  label: label, 
  containers: [
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'kubectl', image: 'cnych/kubectl', command: 'cat', ttyEnabled: true)
  ], 
  volumes: [
    hostPathVolume(mountPath: '/root/.m2', hostPath: '/var/run/m2'),
    hostPathVolume(mountPath: '/home/jenkins/.kube', hostPath: '/root/.kube'),
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
  ],
  serviceAccount: 'jenkins2'
) {
  node(label) {
      stage('docker info') {
          container('docker') {
              sh 'docker info'
          }
      }

      stage('kubectl version') {
          container('kubectl') {
              sh 'kubectl version'
          }
      }
  }
}